name: gocredits
on:
  push:
    branches: ["tagpr-from-*"]

permissions:
  pull-requests: write
  packages: write
  contents: write
  actions: write

jobs:
  tagpr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          persist-credentials: true
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v5
        with:
          go-version: "1.25.3"
      - uses: mashiike/action-gocredits@d2bc7fc94c93a27761800f03408ca00c3e9b3e85 # v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
